% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Jun-2021 20:52:53
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('JSTModul7.mat');

bias = -1;

bobot = [1 1];

input = ...
  [1 1 0 0;
   1 0 1 0];

net = saveVarsMat.net; % <1x1 network> unsupported class

output = [1 1 1 0];

target = [1 1 1 0];

clear saveVarsMat;
